### ISSUE TITLE
[Pitch] Add Chord

### ISSUE THREAD

**Issue by jsbean** [dn-m/Music#85]
cc @bwetherfield (and @brianlheim if interested).

Add `Chord` functionality to the `Pitch` module. The `Chord` structure would be an abstract musical concept (i.e., no knowledge of `SpelledPitch`). 

Perhaps there could be two types which are related: `OrderedInterval.Collection`,

```Swift
extension OrderedInterval {
    struct Collection {
        let intervals: [OrderedInterval]
    }
}
```

and `Chord`.

```Swift
struct Chord {
    let first: Pitch
    let intervals: OrderedInterval.Collection
    init(intervals: OrderedInterval.Collection, at first: Pitch) { ... }
    init <S> (_ sequence: S) where S: Sequence, S.Element == Pitch { ... }
}
```

**Comment by jsbean** [comment]
Orbiting types could be `Chord.Descriptor`, which would be isomorphic with a `Chord` (`"C" major` <-> `Chord(intervals: [4,3], at: 60)`)

**Comment by jsbean** [comment]
Some helper `static var`s could be added:

```Swift
extension OrderedInterval.Collection {
    static var major: OrderedInterval.Collection = [4,3]
    static var minor: OrderedInterval.Collection = [3,4]
}
```

So as to create the following call site:

```Swift
let fSharpMajor = Chord(intervals: .major, at: 66)
```

**Comment by jsbean** [comment]
An interesting topic of discussion would be how to handle extensions properly (ninths, elevenths, thirteenths`, etc.) and alterations (`sharp5, flat5, sharp9, flat9`, etc.).

**Comment by bwetherfield** [comment]
I support 
```swift 
init(intervals: OrderedInterval.Collection, at first: Pitch) { ... }
```
but I wonder if it would be good to have underlying storage of the form
```swift
    let first: Pitch
    let intervals: UnorderedInterval.Collection
```
... with some canonical ordering from lowest pitch.

**Comment by bwetherfield** [comment]
Okay so storing pitches rather than a single pitch plus intervals? Of course the other representation can be uncovered _via_ a computed property whichever route you take

**Comment by jsbean** [comment]
Yeah, I think `Chord` makes more sense to be stored as a `Collection`, as it has a fixed count of values (so we might as well use a storage mechanism that models that).

Whereas `Scale` may have no known bounds. For example, when someone writes that piece which has pitches from the b quarter flat "57 octaves lower than middle-C are rumbling away from a supermassive black hole in the Perseus cluster" up to dog-whistle range, we will be in good shape.
