### ISSUE TITLE
[Pitch] Add Scale

### ISSUE THREAD

**Issue by jsbean** [dn-m/Music#86]
cc @bwetherfield 

Add the `Scale` struct. Similarly to the `OrderedInterval.Collection`/`Chord` pairing [here](https://github.com/dn-m/Music/issues/85), there is an abstract form and a concrete form. In fact, the underlying structure may be identical to that of the `Chord` universe, but with different affordances.

```Swift
struct Scale {
    let intervals: OrderedInterval.Collection
    let first: Pitch
}
```

**Comment by bwetherfield** [comment]
Similar to my comment on #85, do you want to insist that scales are monotonically increasing / decreasing in pitch? Hence
```swift
    let intervals: UnorderedInterval.Collection
    let lowest: Pitch
```
or even 
```swift
enum Sense {
    case ascending
    case descending
}

struct Scale {
    let sense: Sense
    let first: Pitch
    let intervals: UnorderedInterval.Collection
}
```

**Comment by jsbean** [comment]
Ahh, hmm. This is interesting. I had the same feeling when writing [Scale.IntervalPattern.melodicMinorAscending](https://github.com/dn-m/Music/pull/88/files#diff-57e2c960af393683fef7d692148366faR27).

**Comment by jsbean** [comment]
I'd like to pivot `Scale` to more of an infinite, looping `Sequence` than a concrete array of pitches, so that it is more logically coherent to ask for the scale degree of a pitch outside of the first octave.

**Comment by jsbean** [comment]
But I was considering `Scale` more of a static collection of pitches rather than coupling the iteration direction (`.ascending / .descending`) into the type itself.

**Comment by jsbean** [comment]
The aforementioned `OrderedInterval.Collection` is now `Scale.IntervalPattern`. I think it made more sense to have unique interval patterns for `Chord` and `Scale` concepts as they do have different affordances down the line.

**Comment by jsbean** [comment]
Part of me wants to elevate `Scale` to a `protocol`. At some point, I would like to have things like `submediant` or `supertonic` as properties (known at compile time) of heptatonic scales. These wouldn't be applicable to one's octatonic or custom non-EDO12 mathematically generated alien scale.

**Comment by jsbean** [comment]
My main desire with these structures in the short term is to provide an interface for a choose-your-own-harmonic-adventure type thing, where the chords from a given scale degree can be decoupled from the concrete scale (c major, etc.).

**Comment by jsbean** [comment]
More ramblings: I think it'd be wise to build out a `ScaleDegree` structure, with different representational affordances. The `ScaleDegree` might have an `index` (`0`, `1` ...), and depending on the context of the `Scale` (major, minor, etc.) it may be represented in different ways (`I` or `i`, etc.).

Tell me if I am wrong here: You can put a circumflex over a letter ("Î") but not a number ("ˆ1"), which is how its used in scale degree notation. Wikipedia uses images :o. I'm sure smufl has a code point for this, though.

**Comment by bwetherfield** [comment]
> I'd like to pivot `Scale` to more of an infinite, looping `Sequence` than a concrete array of pitches, so that it is more logically coherent to ask for the scale degree of a pitch outside of the first octave.

Would it make sense for `Scale` to be of the form 
```swift
struct Scale {
    pitchClasses: [Pitch.Class]
}
```
This could be an important component of the difference between a `Chord` (cf. #85)  and a `Scale`? Is a `Scale` an example of something more general like a pitch-set, which is more a collection of pitch classes (octave-invariant)? Or is a harmonic series a kind of scale, for example - not octave-invariant ... ?

**Comment by jsbean** [comment]
Hmm, yes. I was thinking that, too. For now, the `Scale.IntervalCollection` is built upon `Pitch` values for the sake of simplicity (as they are most-often used within simple arithmetic (e.g., summation, addition with `root`)).

See #95 where `Scale` is now implemented as a (potentially) infinite looping `Sequence`.

This implementation also does not assume octave invariance. (Currently, there is a bool property: `isOctaveRepeating` which checks if the intervals add up to `12`).
